services:
  # keycloak:
  #   image: quay.io/keycloak/keycloak:24.0.3
  #   command: start-dev #as we are not in production
  #   environment:
  #     KC_DB: postgres
  #     KC_DB_URL_HOST: postgres_keycloak #linked to the postgres service
  #     KC_DB_URL_DATABASE: keycloak
  #     KC_DB_USERNAME: keycloak
  #     KC_DB_PASSWORD: password
  #     KC_DB_SCHEMA: public
  #     #The env below are specific for the keycloak entrance console
  #     KEYCLOAK_ADMIN: admin
  #     KEYCLOAK_ADMIN_PASSWORD: admin
  #     KC_PROXY: edge
  #     KC_HOSTNAME_ADMIN_URL: https://localhost:8443
  #     KC_HOSTNAME_URL: https://localhost:8443

  #   depends_on:
  #     postgres_keycloak:
  #       condition: service_healthy
    
  # postgres_keycloak:
  #   image: postgres:14.2
  #   command: postgres -c 'max_connections=200'
  #   volumes:
  #     - pgdata_keycloak:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_DB: keycloak
  #     POSTGRES_USER: keycloak
  #     POSTGRES_PASSWORD: password
  #   healthcheck:
  #     test: "exit 0"
  #   ports:
  #     - "5436:5432"
      
  nginx:
    build: ./nginx
    depends_on:
      #- keycloak
      - react-service
      - node-service1
      - node-service2
    restart: always
    ports:
      - '8080:80' #http
      - '443:443' #https
      #- '8443:8443'
  react-service:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      # - keycloak
      - node-service1
      - node-service2
  node-service1:
    build:
      dockerfile: Dockerfile.dev
      context: "./backend"
    volumes:
      - ./backend:/app #link both directories
      - /app/node_modules
      
    depends_on:
      - mongo-service
    environment:
      - MONGO_USER=mongouser
      - JWT_SECRET=example
      - MONGO_URL=mongo-service
      - MONGO_PASSWORD=mongopassword
  node-service2:
    build:
      dockerfile: Dockerfile.dev
      context: "./backend"
    volumes:
      - ./backend:/app #link both directories
      - /app/node_modules
    depends_on:
      - mongo-service
    environment:
      - MONGO_USER=mongouser
      - JWT_SECRET=example
      - MONGO_URL=mongo-service
      - MONGO_PASSWORD=mongopassword
  mongo-service:
    image: "mongo:latest"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongouser
      - MONGO_INITDB_ROOT_PASSWORD=mongopassword
    ports:
    - 27017:27017
    

# volumes: 
#   pgdata_keycloak:

#NETWORKS ARE NOT NEEDED AS NGINX IS IN CHARGE OF ROUTING EVERYTHING