services:
  nginx:
    build: ./nginx
    depends_on:
      - react-service
      - node-service1
      - node-service2
    restart: always
    ports:
      - '8080:80' #http
      - '443:443' #https
  react-service:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - node-service1
      - node-service2
  node-service1:
    build:
      dockerfile: Dockerfile
      context: "./backend"
    volumes:
      - ./backend:/app #link both directories
      - /app/node_modules
      
    depends_on:
      - mongo-service
    environment:
      - MONGO_USER=mongouser
      - JWT_SECRET=example
      - MONGO_URL=mongo-service
      - MONGO_PASSWORD=mongopassword
  node-service2:
    build:
      dockerfile: Dockerfile
      context: "./backend"
    volumes:
      - ./backend:/app #link both directories
      - /app/node_modules
    depends_on:
      - mongo-service
    environment:
      - MONGO_USER=mongouser
      - JWT_SECRET=example
      - MONGO_URL=mongo-service
      - MONGO_PASSWORD=mongopassword
  mongo-service:
    image: "mongo:latest"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongouser
      - MONGO_INITDB_ROOT_PASSWORD=mongopassword
      #for testing the connection with mongoDB compass, needed to add db=admin
    ports:
    - 27017:27017

#NETWORKS ARE NOT NEEDED AS NGINX IS IN CHARGE OF ROUTING EVERYTHING